name: CI

on:
  schedule:
  - cron: '0 17-22 * * *'
jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - name  : Notification_success
        if    : ${{ success() }}
        run   : curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_TO }} -d text='привет'
      
