name: CI

on:
  push:

  schedule:
#time UTC (Armenia +4UTC)
    - cron: '20 13-18 * * *'
jobs:
  notifier:
    runs-on: ubuntu-latest
    steps:
      - name  : Notification_success
        run   : curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage -d chat_id=${{ secrets.TELEGRAM_TO }} -d text='О великий хозяин @Godlikeprofi проверка работоспособности'
      
